---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-13.04
    run_list:
    - recipe[apt::default]
  - name: debian-6.0.8
    run_list:
    - recipe[apt::default]
  - name: debian-7.2.0
    run_list:
    - recipe[apt::default]
  - name: centos-6.5
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[mod_security::default]
    attributes:
